import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="max-w-4xl relative mx-auto px-8 lg:px-0">
          <div className="pt-10">
            <Link href="/">
              <h1 className="text-3xl font-semibold">
                rsvp<span className="text-sky-700">.</span>it
              </h1>
            </Link>
            <div className="p-4"></div>
          </div>
          {children}
        </section>
      </body>
    </html>
  );
}
